# Cloudflare Pages configuration
name = "solar-quote-app"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "public"

[[pages.env_vars]]
name = "NODE_ENV"
value = "production"

[pages.functions]
directory = "functions"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[pages.d1_databases]
# Add D1 database binding if needed in the future
# solar_db = { database_name = "solar-quote-db", database_id = "your-database-id" }